name: funky_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  hexcolor: ^2.0.7
  http: ^0.13.4
  fluttertoast: ^8.0.8
#  firebase_auth: ^1.2.0
#  firebase_core: ^1.2.0
#  firebase_auth: ^3.1.4
#  firebase_core: ^1.8.0
#  flutter_facebook_auth: ^4.3.3
#  google_sign_in: ^5.2.4

  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.2.0
  twitter_login: ^4.0.1
#  webview_flutter: ^3.0.0
#  flutter_webview_plugin: ^0.4.0

  get_storage: ^2.0.3
#  simple_auth_flutter: ^2.0.11
  flutter_staggered_grid_view: 0.4.1

  cloud_firestore: 3.1.10
  video_player: ^2.2.18
#  better_player: ^0.0.70
  pinput: ^1.2.0
  dropdown_button2: ^1.0.7
  image_picker: ^0.8.2
  shared_preferences: ^2.0.13
  image_editor_plus: ^0.1.3
  loading_indicator: ^3.0.2
  video_editor: ^1.2.0
  helpers: ^1.1.4
  photo_manager: ^1.3.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: PB
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
    - family: PBI
      fonts:
        - asset: assets/fonts/Product Sans Bold Italic.ttf
    - family: PI
      fonts:
        - asset: assets/fonts/Product Sans Italic.ttf
    - family: PR
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
